language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - npm install zombie
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpspec run --format dot --no-interaction
    - vendor/bin/behat --no-snippets --no-paths --verbose
