parameters:
    # Index definition
    bs_crudify.definition.index.builder_registry.class: Bs\CrudifyBundle\Definition\Index\Builder\Registry\BuilderRegistry
    bs_crudify.definition.index.builder.static.class: Bs\CrudifyBundle\Definition\Index\Builder\StaticBuilder
    bs_crudify.definition.index.builder.dynamic.class: Bs\CrudifyBundle\Definition\Index\Builder\DynamicBuilder

    # Definitions registry and loader
    bs_crudify.definition.registry.class: Bs\CrudifyBundle\Definition\Registry\SymfonyDefinitionRegistry
    bs_crudify.definition.loader.class: Bs\CrudifyBundle\Definition\Loader\DIDefinitionLoader

    # Routing loader
    bs_crudify.routing_loader.class: Bs\CrudifyBundle\Routing\CrudifyLoader

    # Resolvers
    bs_crudify.resolver.controller.class: Bs\CrudifyBundle\Resolver\ControllerResolver
    bs_crudify.resolver.form_options.class: Bs\CrudifyBundle\Resolver\FormOptionsResolver
    bs_crudify.resolver.form.class: Bs\CrudifyBundle\Resolver\FormResolver
    bs_crudify.resolver.grid.class: Bs\CrudifyBundle\Resolver\GridResolver
    bs_crudify.resolver.identity.class: Bs\CrudifyBundle\Resolver\IdentityResolver
    bs_crudify.resolver.link.class: Bs\CrudifyBundle\Resolver\LinkResolver
    bs_crudify.resolver.query.class: Bs\CrudifyBundle\Resolver\QueryResolver
    bs_crudify.resolver.query_modifier.class: Bs\CrudifyBundle\Resolver\QueryModifierResolver
    bs_crudify.resolver.object_retriever.class: Bs\CrudifyBundle\Resolver\ObjectRetrieverResolver

    # Controller
    bs_crudify.controller.class: Bs\CrudifyBundle\Controller\CrudifyController
    bs_crudify.controller.base.class: Bs\CrudifyBundle\Controller\BaseController

    # Twig extension
    bs_crudify.twig.extension.class: Bs\CrudifyBundle\Twig\CrudifyExtension

    # Security voter
    bs_crudify.security.access.crudify_voter.class: Bs\CrudifyBundle\Security\Authorization\Voter\CrudifyAccessVoter

    # Form options providers
    bs_crudify.form.options.provider.basic.class: Bs\CrudifyBundle\Form\OptionsProvider\BasicOptions

    # Default object retriever
    bs_crudify.query.retriever.repository.class: Bs\CrudifyBundle\Query\RepositoryObjectRetriever

services:
    # Index definition registry
    bs_crudify.definition.index.builder_registry:
        class: %bs_crudify.definition.index.builder_registry.class%

    # The index definition builder that builds based on static field definitions
    bs_crudify.definition.index.builder.static:
        class: %bs_crudify.definition.index.builder.static.class%
        public: false
        tags:
            - { name: bs_crudify.index_builder, alias: static }

    # The index definition builder that builds automatically based on the entity provided
    bs_crudify.definition.index.builder.dynamic:
        class: %bs_crudify.definition.index.builder.dynamic.class%
        public: false
        arguments:
            - @doctrine
        tags:
            - { name: bs_crudify.index_builder, alias: dynamic }


    # Loader for definitions from config
    bs_crudify.definition.loader:
        class: %bs_crudify.definition.loader.class%
        public: false
        arguments:
            - @doctrine
            - @bs_crudify.definition.index.builder_registry
        calls:
            - [setContainer, [@service_container]]
            - [setTemplates, [%bs_crudify.template_defaults%]]


    # The registry that contains the definitions for different entities
    bs_crudify.definition.registry:
        class: %bs_crudify.definition.registry.class%
        arguments:
            - @bs_crudify.definition.loader
        calls:
            - [addMappings, [%bs_crudify.definitions%]]


    # Custom routing loader for crudify
    bs_crudify.routing_loader:
        class: %bs_crudify.routing_loader.class%
        arguments:
            - %bs_crudify.default_mapping%
        tags:
            - { name: routing.loader }

    bs_crudify.resolver.controller:
        class: %bs_crudify.resolver.controller.class%
        arguments:
            - %bs_crudify.default_controller%
        calls:
            - [setContainer, [@service_container]]

    bs_crudify.resolver.form_options:
        class: %bs_crudify.resolver.form_options.class%
        calls:
            - [setContainer, [@service_container]]

    bs_crudify.resolver.form:
        class: %bs_crudify.resolver.form.class%
        calls:
            - [setContainer, [@service_container]]

    bs_crudify.resolver.grid:
        class: %bs_crudify.resolver.grid.class%
        arguments:
            - @knp_paginator

    bs_crudify.resolver.identity:
        class: %bs_crudify.resolver.identity.class%
        arguments:
            - @doctrine

    bs_crudify.resolver.link:
        class: %bs_crudify.resolver.link.class%
        arguments:
            - @router
            - @bs_crudify.resolver.identity

    bs_crudify.resolver.query_modifier:
        class: %bs_crudify.resolver.query_modifier.class%
        calls:
            - [setContainer, [@service_container]]

    bs_crudify.resolver.query:
        class: %bs_crudify.resolver.query.class%
        arguments:
            - @bs_crudify.resolver.identity
            - @bs_crudify.resolver.query_modifier

    bs_crudify.resolver.object_retriever:
        class: %bs_crudify.resolver.object_retriever.class%
        calls:
            - [setContainer, [@service_container]]

    # The controller that handles requests
    bs_crudify.controller:
        class: %bs_crudify.controller.class%
        calls:
            - [setContainer, [@service_container]]

    # Default base controller
    bs_crudify.controller.base:
        class: %bs_crudify.controller.base.class%
        calls:
            - [setContainer, [@service_container]]

    # Twig extension
    bs_crudify.twig.extension:
        class: %bs_crudify.twig.extension.class%
        arguments:
            - @property_accessor
            - @bs_crudify.resolver.link
            - @bs_crudify.resolver.controller
            - @bs_crudify.definition.registry
        tags:
            - { name: twig.extension }

    # Security voter
    bs_crudify.security.access.crudify_voter:
        class: %bs_crudify.security.access.crudify_voter.class%
        public: false
        arguments:
            - %bs_crudify.security.default_access%
        tags:
            - { name: security.voter }

    # Basic form options provider
    bs_crudify.form.options.provider.basic:
        class: %bs_crudify.form.options.provider.basic.class%

    # Default object retriever
    bs_crudify.query.retriever.repository:
        class: %bs_crudify.query.retriever.repository.class%
